config/routes.rb
Rails.application.routes.draw do
  get 'all-timezones' => 'trips#timezones'
  get 'trip-:url/find-events' => 'ideas#find_events', as: :find_events
  get 'trip-:url/find-food' => 'ideas#find_food', as: :find_food
  get 'trip-:url/scenery' => 'ideas#scenery', as: :scenery

  get 'trip-:url/invite' => 'group_trips#invite', as: :invite_friend
  post 'trip-:url/invite' => 'group_trips#send_invite'
  patch 'trip-:url/:response' => 'group_trips#rsvp', as: :rsvp
  get 'invites' => 'group_trips#invites', as: :invites

  delete 'trip-:url/leave' => 'group_trips#leave_trip', as: :leave_trip
  delete 'trip-:url/uninvite-:tag' => 'group_trips#uninvite', as: :uninvite

  delete 'trip-:url/delete' => 'trips#destroy', as: :delete_trip
  get 'trip-:url' => 'trips#show', as: :trip
  get 'trip-:url/edit' => 'trips#edit', as: :edit_trip
  post 'trip-:url/edit' => 'trips#update'
  get 'trips/new' => 'trips#new', as: :new_trip
  post 'trips/new' => 'trips#create'
  
  get 'past-trips' => 'users#past_trips', as: :past_trips
  get 'dashboard' => 'users#show', as: :dashboard
  get 'account' => 'users#edit', as: :account
  patch 'account' => 'users#update'

  post 'trip-:url/add-:title/:category/address-:address' => 'ideas#add_idea', as: :add_idea
  post 'trip-:url' => 'ideas#create', as: :new_idea
  get 'trip-:url/idea-:id' => 'ideas#show', as: :idea
  put 'trip-:url/idea-:id/edit' => 'ideas#update', as: :edit_idea
  delete 'trip-:url/idea-:id/delete' => 'ideas#destroy', as: :delete_idea
  get 'trip-:url/ideas' => 'ideas#index'

  post 'signup' => 'users#create'
  post 'login' => 'users#authenticate'
  delete 'logout' => 'users#logout', as: :logout
 
  get 'password_reset' => 'password_resets#new', as: :password_reset
  post 'password_reset' => 'password_resets#create'
  get 'password_reset/:token' => 'password_resets#edit', as: :confirm_reset
  patch 'password_reset/:token' => 'password_resets#update'

  resources :users do 
    resources :trips, only: [:show, :delete] do 
      resources :ideas, only: [:show, :delete]
    end
  end

  root 'home_pages#home'


  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/trip.rb
class Trip < ActiveRecord::Base
    include ValidDates

    has_many :invites, class_name: "Relationship",
                     foreign_key: "trip_id",
                     dependent: :destroy
    has_many :users, through: :invites

    has_many :ideas, dependent: :destroy

    validates :name, :city, :country, 
              presence: true
    
    validates :name, length: { maximum: 50 }
    validates_uniqueness_of :url

    after_create :gen_trip_url

    def trip_end
        if Date.today > end_date
            self.update_attribute(:ended?, true)
        end
    end

    ## CALLBACKS ## 
    def gen_trip_url 
        update_column :url, SecureRandom.urlsafe_base64
        not_unique = Trip.where(url: self.url).length > 1
        raise ActiveRecord::RecordNotUnique if not_unique
        retries = 5
    rescue ActiveRecord::RecordNotUnique => e
        retries -= 1
        retry if retries > 0
        raise e, "An error has occurred, try again later"
    end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :require_login

  def timezones
    @timezones = {}
    ActiveSupport::TimeZone.all.each do |zone|
      @timezones[zone.name] = zone.utc_offset
    end
    render json: @timezones
  end

  def show
    @trip = current_trips.find_by_url(params[:url])
    @action = 'create'
    @pending = @trip.invites.where(rsvped?: nil)
    @going = @trip.invites.where(going?: true)

    @group = getIdeas(@trip)
  end

  def new
    @trip = current_trips.build
    @invite = @trip.invites.build
    @action = 'new' # for getPath helper
  end

  def create
    @trip = current_trips.build(trip_params)
    @trip.creator = current_user.id
    @action = 'create'
    if @trip.save
      @invite = @trip.invites.create(user_id: current_user.id,
                                     email: current_user.email,
                                     user_tag: current_user.tag,
                                     rsvped?: true, going?: true)
      if @invite.present?
        redirect_to trip_path(@trip.url)
      else
        flash[:danger].now = "error"
        render :new
      end
    else
      @errors = @trip.errors
      render :new
    end
  end

  def edit
    @action = 'edit'
    @trip = current_trips.find_by(url: params[:url])
  end

  def update
    @action = 'update'
    @trip = current_trips.find_by(url: params[:url])
    if @trip.update_attributes(trip_params)
      redirect_to trip_path(@trip.url)
    else
      @errors = @trip.errors
      render :edit
    end
  end

  def destroy
    @trip = current_trips.find_by(url: params[:url])
    @trip.destroy
    redirect_to dashboard_path
  end

  private
    def trip_params
      params.require(:trip).permit(:name, :url, :start_date,
                                   :end_date, :city,
                                   :country, :creator, :ended?)
    end
end

app/helpers/trip_helper.rb
module TripHelper
    def getInvite(trip)
        Relationship.where(trip_id: trip.id, user_id: current_user.id).first
    end

    def tripEnded?(trip)
        Date.today > trip.end_date
    end

    def creator(trip)
        User.find(trip.creator)
    end

    def creator?(invite=nil, trip=nil)
        if invite
            creator( invite.trip ) == current_user 
        else
            creator(trip) == current_user 
        end
    end

    def currency
        begin 
          url = "http://api.fixer.io/latest"
          rates = HTTParty.get(url)
          JSON.parse(rates.body)
        rescue JSON::ParserError => e
          "Something went wrong--please refresh the trip page."
        end
    end

    def getCurrency
        list = currency['rates'].keys
        list << currency['base']
        list.sort!
    end

    def timezones
        timezone_list = []
        ActiveSupport::TimeZone.all.each do |zone|
            timezone_list << zone.name
        end
        timezone_list
    end

    def getRSVP(invite)
        if invite.rsvped?
            invite.going? && !invite.maybe? ? "GOING" : "MAYBE"
        else
            "PENDING"
        end
    end

    def linkRSVP(invite)
        yes_link = link_to 'YES', rsvp_path(invite.trip.url, 'yes'), method: :patch
        maybe_link =  link_to 'MAYBE', rsvp_path(invite.trip.url, 'maybe'), method: :patch
        no_link = link_to 'NO', leave_trip_path(invite.trip.url), method: :delete, data: {confirm: 'You sure?'}

        case getRSVP(invite)
        when "GOING"
           [maybe_link, no_link]
        when "MAYBE"
            [yes_link, no_link]
        else
            [yes_link, maybe_link, no_link]
        end
    end

    def days_left(startdate, enddate)
        ( (startdate - enddate)/86400 ).ceil
    end

    def count(days)
        pluralize(days.abs, 'day')
    end

    def trip_countdown
        if days_left(@trip.start_date, Time.now) > 1
            num_days = days_left(@trip.start_date, Time.now)
            countdown = "Starts in #{count(num_days)}"
        elsif days_left(@trip.start_date, Time.now) === 1
        	countdown = "Starts tomorrow!"
        elsif @trip.start_date <= Time.now && @trip.end_date >= Time.now
        	num_days = days_left(Time.now, @trip.start_date)
        	countdown = "Started #{count(num_days)} ago"
        elsif @trip.end_date < Time.now
        	num_days = days_left(Time.now, @trip.end_date)
        	countdown = "Ended #{count(num_days)} ago"
        end
    end

    def headcount(trip)
        count = 0
        trip.invites.each do |invite|
            if invite.going?
                count+= 1
            end
        end
        pluralize(count, 'person')
    end
end

app/views/trips/_calendar.erb
<table ng-repeat="month in getMonths">
    <thead>
        <th colspan=7>
            <h1>{{ month }}</h1>
        </th>
    </thead>

    <tbody>
        <tr class="calendar--day">
            <td ng-repeat="weekday in weekdays">
                {{ weekday }}
            </td>
        </tr>
           
        <tr class="calendar--week">
            <td ng-repeat="day in firstWeekOfMonth(month) track by $index">
                <div class="calendar--date" ng-class="{'trip-date': tripDates(month,day)}">
                    {{ day }}
                </div>
            </td>
        </tr>
      
        <tr class="calendar--week" ng-repeat="week in [0,1,2,3]">
            <td ng-repeat="day in remainingWeeks(month) track by $index" ng-if="notMaxDays(month, day,week)">
                <div class="calendar--date" ng-class="{'trip-date': tripDates(month, days.getDay(day,week))}">
                    {{ days.getDay(day,week) }}
                </div>
            </td>
        </tr>
    </tbody>
</table>

app/views/trips/_date_panels.erb
<div class="calendar--short" ng-init="buildTrip()">
    <div class="calendar--slider" slick-slider="{infinite: false,slidesToShow: 3,centerMode: true,focusOnSelect: true,centerPadding: '60px', asNavFor: '.todays--events'}">
        <div class="calendar--day" ng-repeat="day in trip track by $index" > 
            <span class="month">{{ months[day.getMonth()] }}</span>
            <span class="date"> {{ day.getDate() }}</span>
            <span class="day">{{ getWkday(day) }}</span>
        </div>
    </div>

    <div class="todays--events" slick-slider="{slidesToShow: 1, fade:true, arrows: false, asNavFor: '.calendar--slider'}">
  
    	<div class="slider--events" ng-repeat="day in trip track by $index">
	    	<div ng-repeat="idea in ideas.food" ng-if="matchDate(day, idea)">
	    		<h2>{{idea.title}}</h2>
	    		<p>Where:{{idea.location}}</p>
	    		<p>{{idea.start_time}}</p>
			</div>
	    	<div ng-repeat="idea in ideas.event" ng-if="matchDate(day, idea)">
	    		<h2>{{idea.title}}</h2>
	    		<p>Where:{{idea.location}}</p>
	    		<p>{{idea.start_time}}</p>
	    	</div>
	    	<div ng-repeat="idea in ideas.activity" ng-if="matchDate(day, idea)">
	    		<h2>{{idea.title}}</h2>
	    		<p>Where:{{idea.location}}</p>
	    		<p>{{idea.start_time}}</p>
	    	</div>
	    </div>
	    
	</div>

</div>

app/views/trips/_header.erb
<header> 
  <h1><%= "#{@trip.name}" %></h1>
  <p> You are going to <strong><%= "#{@trip.city.capitalize}, #{@trip.country}" %></strong> 
  on <%= "#{format_date(@trip.start_date)} to #{format_date(@trip.end_date)}" %></p>
  
  <div><%= trip_countdown %></div>
  
  <div>
    <%= headcount(@trip) %> 
    <%= tripEnded?(@trip) ? "went" : "going" %> 
     on this trip<br/>

    <% @going.each do |invite| %>
      <%= invite.user.name %> 
        <% if invite.user == @trip.creator %> 
        (Organizer)
        <% else %> 
          | <%= !creator?(nil, @trip) ? leave(@trip) : uninvite(@trip, invite) %>
        <% end %> 
          <br/>

    <% end %> 
    </p>
  </div>
</header>

app/views/trips/_ideas.erb
<div class="trip--list">           
    <div class="list-group" ng-show="tab.isSet(1)">  
        <% if !@food.empty? %>             
            <% @food.each do |idea| %>
                <div class="list-group-item">
                <h4 class="list-group-item-heading"><%= idea.title %></h4>
                <span class="badge"><%= link_to "delete", [current_user,@trip, idea], method: :delete, data: {confirm: "You sure?"} %></span>
                <span class="badge"><%= link_to "edit", edit_idea_path(@trip.url, idea.id) %> </span>
                <p class="list-group-item-text">
                When: <%= format_date(idea.start_date) %> -  <%= format_date(idea.end_date) %><br>
                Where: <%= idea.location%> <br>
                Suggested by: <%= idea_user(idea) %></p>
                </div>
            <% end %>
        <% else %>
            <li>Nothing planned. Add your idea</li>
        <% end %>
    </div>

    <ul class="list-group" ng-show="tab.isSet(2)">
        <% if !@activity.empty? %>
            <% @activity.each do |idea| %>
                <div class="list-group-item">
                <h4 class="list-group-item-heading"><%= idea.title %></h4>
                <span class="badge"><%= link_to "delete", [current_user,@trip, idea], method: :delete, data: {confirm: "You sure?"} %></span>
                <span class="badge"><%= link_to "edit", edit_idea_path(@trip.url, idea.id) %> </span>
                <p class="list-group-item-text">
                When: <%= format_date(idea.start_date) %> -  <%= format_date(idea.end_date) %><br>
                Where: <%= idea.location%> <br>
                Suggested by: <%= idea_user(idea) %></p>
                </li>
            <% end %>
        <% else %>
            <li style="padding:10px 15px">Nothing planned. Add your idea</li>
        <% end %>
    </ul>
             
    <ul class="list-group" ng-show="tab.isSet(3)">
        <% if !@event.empty? %>
             <% @event.each do |idea| %>
                 <div class="list-group-item">
                <h4 class="list-group-item-heading"><%= idea.title %></h4>
                <span class="badge"><%= link_to "delete", [current_user,@trip, idea], method: :delete, data: {confirm: "You sure?"} %></span>
                <span class="badge"><%= link_to "edit", edit_idea_path(@trip.url, idea.id) %> </span>
                <p class="list-group-item-text">
                When: <%= format_date(idea.start_date) %> -  <%= format_date(idea.end_date) %><br>
                Where: <%= idea.location%> <br>
                Suggested by: <%= idea_user(idea) %></p>
            <% end %>
        <% else %>
            <li  style="padding:10px 15px">Nothing planned. Add your idea</li>
       <% end %>
    </ul>
   
</div>

app/views/trips/_invite_form.erb
<%= form_for(:relationship, url: {controller: 'trips', action: 'send_invite'}) do |f| %>                     
                                  
    <%= label_tag(:email, "Friend email")%><br>
    <%= f.text_field :email %>

    <p><%= f.submit "Send", class: 'btn' %></p>

<% end %>

app/views/trips/_navbar.erb
<nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
        <li>
            <a href="#"class="dropdown-toggle" data-toggle="dropdown">Account<span class="caret"></span></a>
            <ul class="dropdown-menu"> 
                <li><%= link_to 'Me', dashboard_path %></li>
                <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            </ul>
        <li>
            <a href="#"class="dropdown-toggle" data-toggle="dropdown">Trip<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li> <%= link_to 'New trip', new_trip_path %></li>
                <% if creator?(nil, @trip) %>
                    <li><%= link_to 'Edit trip', edit_trip_path(@trip.url) %></li>
                <% end %>
                <% if !tripEnded?(@trip) %>
                    <li> <%= link_to 'Invite', invite_friend_path(@trip.url) %></li>
                <% end %>
            </ul>
        </li>
        <li><a href="#"class="dropdown-toggle" data-toggle="dropdown" >Discover<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><%= link_to 'Restaurants', find_food_path(@trip.url) %></li>
                <li><%= link_to 'Attractions', find_events_path(@trip.url) %></li>
                <li>Scenery</li>
            </ul>
        </li>
    </ul>
</nav>

app/views/trips/_rsvp.erb
<%= getRSVP(invite) %> 
        <% linkRSVP(invite).each do |link| %>
           | <%= link %> 
        <% end %> 

app/views/trips/_trip_form.erb
<%= form_for(:trip, url: getPath('trips', @action)) do |f| %>
    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1">Trip Name</span>
      <%= f.text_field :name, class: 'form-control'%>
    </div>

    <div class="input-group">
      <span class="input-group-addon" id="basic-addon2"> When</span>
    <%= f.text_field :start_date, class: 'new-trip', placeholder: 'Start Date' %>
    -
    <%= f.text_field :end_date, class: 'new-trip', placeholder: 'End Date' %> 
    </div> 

    <div class="input-group">
        <span class="input-group-addon" id="basic-addon3">City<br></span>
         <%= f.text_field :city , class: 'form-control'%>
    </div>
    
     <div class="input-group">
        <span class="input-group-addon" id="basic-addon4">Country</span>
        <%= f.text_field :country, class: 'form-control'%>
    </div>

    <p><%= f.submit "Submit", class: 'btn' %></p>

<% end %>
</div>

app/views/trips/edit.erb
<%= render 'navbar' %>

<h1 class="page-header" >Edit Trip</h1>

<%= render 'shared/form_error' %>
<%= render 'trip_form' %> 

<div> <button class="btn">Back</button></div>

app/views/trips/find_food.erb
<%= render 'navbar' %>

<header> 
  <h1><%= "#{@trip.name}" %></h1>
  <p> You are going to <strong><%= "#{@trip.city.capitalize}, #{@trip.country}" %></strong> 
  on <%= "#{format_date(@trip.start_date)} to #{format_date(@trip.end_date)}" %></p>
  
  <div><%= trip_countdown %></div>
  
  <div>
    <%= headcount(@trip) %> 
    <%= tripEnded?(@trip) ? "went" : "going" %> 
     on this trip<br/>

    <%= creator(@trip).name %> (Organizer)<br/>
    <% @trip.invites.each do |invite| %>
     
      <% if invite.going? && getUser(invite) != creator(@trip) %>
          <%= getUser(invite).name %>  
          <% if current_user = getUser(invite) %>
            | <%= link_to 'leave trip', leave_trip_path(@trip.url), method: :delete, data: {confirm: 'You sure?'} %>
          <% elsif creator?(@trip) %>
            <%= link_to 'uninvite', uninvite_path(@trip.url, getUser(invite).tag), method: :delete, data: {confirm: 'You sure?'} %> 
          <% end %>
      <% end %>

    <% end %> 
    </p>
  </div>
</header>

<section class="content">
<div class="dashboard clearfix">
<h2>Discover Restaurants in <%= @trip.city %></h2>
    <div>
    <%= form_tag find_food_path(@trip.url), method: "get" do %>
        <%= text_field_tag(:neighborhood, "", placeholder: "Neighborhood") %>
        <%= text_field_tag(:cuisine, "", placeholder: "Cuisine") %>
        <%= submit_tag "Search" %> 
    <% end %> 

    </div>

    <p>Sort results by:</p> 
    <%= form_tag find_food_path(@trip.url), method: "get" do %>  
        <%= radio_button_tag(:sort, 0) %>
        <%= label_tag(:relevance, "Relevance") %>
        <%= radio_button_tag(:sort, 1) %>
        <%= label_tag(:distance, "Distance") %>
        <%= radio_button_tag(:sort, 2) %>
        <%= label_tag(:rating, "Rating") %>
        <%= submit_tag "Sort" %> 
    <% end %> 

    <% if !@yelp_error.nil? %>
        <div class="error"> <%= @yelp_error %></div>
    <% else%> 

    
    <table class="discover_yelp">
        <tbody>
         <tr>
        <% @result.businesses.each_with_index do |b, index| %>

        <% if index != 0 && index % 5 === 0 %>
            </tr>
            <tr>
        <% end %>

            <td class="yelp_restaurant">
            <figure style="width:200px"><%= image_tag(b.image_url, alt: "#{b.name}") %> </figure>

            <h3><%= b.name %></h3>  <!-- [ <#%= b.is_closed ? "CLOSED" : "OPEN" %> ] -->
            <span>Rating: <%= b.rating %></span>

            <%= safe_join(b.location.display_address, '<br>'.html_safe) %> 

            Neighborhood: <%#= safe_join(b.location.neighborhoods, ','.html_safe) %>  

            <% if @trip.ideas.find_by_title(b.name) %>
                <strong>ADDED</strong><br/>
            <% else %>
                <%= button_to "Add to itinerary", add_yelp_path(@trip.url, b.name, b.location.display_address), method: :post, data: {confirm: "Add to itinerary?"} %> 
            <% end %> 

            </td>
        <% end %> 
        </tr>
        </tbody>
    </table>
<% end %>
</div>
</section>

app/views/trips/new.erb
<nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
        <li>
          <a href="#"class="dropdown-toggle" data-toggle="dropdown">Account<span class="caret"></span></a>
          <ul class="dropdown-menu"> 
              <li><%= link_to 'Me', dashboard_path %></li>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          </ul>
      <li>
    </ul>
</nav>

<div class="user-profile content">

  <h1 class="page-header">Where are you going?</h1>

  <!--IDEA get rid of state/province. Country is enough -->

  <%= render 'shared/form_error' %>
	<%= render 'trip_form' %> 

</div>

app/views/trips/show.erb
<%= render 'navbar' %>
<%= render 'header' %>

<div class="content" ng-app="trip">
  <div class="dashboard clearfix">

    <section class="trip--calendar">
        <div ng-controller="DateCtrl"  id="trip-data" start_date="<%= start_d %>" end_date="<%= end_d %>" tripURL="<%= @trip.url %>">
            <%= render 'date_panels' %>
        </div>
<!--         <div class="calendar closed">
            <h2>Monthly Calendar</h2>
            <div ng-controller="CalendarCtrl">
                <%#= render 'calendar' %> 
            </div>
        </div> -->

      <div ng-controller="CurrencyCtrl">
        <h2>Exchange Rates</h2>
          <%= text_field_tag "base_amt", '1', size: 5, ng_model: "base_amt" %>
          <%= select_tag "base_currency", options_for_select(getCurrency), ng_model: "base_currency" %> to
          <%= select_tag "new_currency", options_for_select(getCurrency), ng_model: "new_currency" %>

          <%= submit_tag "Convert", class: 'btn', ng_click: "convert(base_amt, base_currency, new_currency)" %>
        <p>
        <span ng-bind="base_amt"></span> 
        <span ng-bind="base_currency"></span>
        <span style="margin-left: 20px">{{ new_amt }}</span>
        <span ng-bind="new_currency"></span>
        </p>
    </div>

    <div ng-controller="TimezoneCtrl">
        <h2>Timezone</h2>
        Time where you are: <%= format_time(Time.now) %><br/>
        Time elsewhere: {{ timezone }}<br/>
        Select timezone: 
          <%= select_tag :timezone, options_for_select(timezones), ng_model: "zone_name" %>
          <%= submit_tag "Select", ng_click: "getTime(zone_name)" %>

      </div>

    </section>
    <aside class="trip--fav" ng-controller="TabController as tab">
        <%= render 'ideas/ideas' %>

       <ol>
           <li> <strong>Todo/ideas</strong>
            <li> Add instagram API</li>
            <li> Responsive page [esp our slider--if we're keeping it]
            <li> Add idea form doesn't close anymore?</li>
            <li> Decide how to let users know they can edit ideas on this page by clicking on them --> maybe highlight text & show an edit icon or even just the word 'edit' on mouseover? </li>
            <li> Maybe have a link/button/tab in the trip header to direct users back to the trip dash instead of having individual links on each page?</li>
            <li> Get email to work in production [for trip invites to unregistered users].</li>
            </li>
          <li> <strong>Changes</strong>    
            <li> Added foursquare API [views/ideas/find_events.erb]
           </li>
           <li> Moved trip header to its own partial [views/trips/_header.erb] for ease of reuse/editing</li>
          </li>
       </ol>

       <div class="idea--form closed">
          <button type="button" class="btn btn-default close-btn">
            <span class="form_close glyphicon glyphicon-remove"></span>
          </button>  
           <%= render 'shared/form_error' %>
           <%= render 'ideas/idea_form' %>
       </div>
    </aside>

  </div>
</div>

app/views/trips/show_group.erb
<%= render 'navbar' %>

<header> 
    <h1><%= "#{@trip.name} Dashboard" %></h1>

     <%= render 'shared/flash_msg' %>
    <p> You are going to <strong><%= "#{@trip.city}, #{@trip.country}" %></strong> on <%= "#{format_date(@trip.start_date)} to #{format_date(@trip.end_date)}" %></p>

 	<div><%= trip_countdown %> to go</div>
    <p>People on this trip: <br>
		<%= @inviter.name %> 
		<% @trip.friends.each do |friend| %> 
		    <%= friend.name %>
		<% end %>
	</p>
</header>

<div class="content clearfix" ng-app="trip">
    <section class="trip--calendar">
        <div ng-controller="DateCtrl"  id="calendar-dates" start_date="<%= start_d %>" end_date="<%= end_d %>">
            <%= render 'date_panels' %>
        </div>
        <div class="calendar closed">
            <h2>Monthly Calendar</h2>
            <div ng-controller="CalendarCtrl">
                <%= render 'calendar' %> 
            </div>
        </div>
    </section>

 <aside class="trip--fav" ng-controller="TabController as tab">
    <h4>Itineary</h4>
	<%= render 'ideas/ideas' %>

	       <button class="idea--form_action btn">Add + </button>

   <div class="idea--form closed">
        <span class="idea--form_close">X close</span>  
       <%= render 'shared/form_error' %>
       <%= render 'ideas/idea_form' %>
   </div>
</aside>

app/views/trips/yelp_results.erb
<%= @result.total %> results total 

<%= @result.businesses.each do |b| %>
    <p>
        <strong><%= b.name %></strong> [ <%= b.is_closed ? "CLOSED" : "OPEN" %> ]<br>
       <%= safe_join(b.location.display_address, '<br>'.html_safe) %>
    </p>
<% end %> 

<p><a href="javascript:history.back()"><< Back</a>