config/routes.rb
Rails.application.routes.draw do
  get 'all-timezones' => 'trips#timezones'
  get 'trip-:url/find-events' => 'ideas#find_events', as: :find_events
  get 'trip-:url/find-food' => 'ideas#find_food', as: :find_food
  get 'trip-:url/scenery' => 'ideas#scenery', as: :scenery

  get 'trip-:url/invite' => 'group_trips#invite', as: :invite_friend
  post 'trip-:url/invite' => 'group_trips#send_invite'
  patch 'trip-:url/:response' => 'group_trips#rsvp', as: :rsvp
  get 'invites' => 'group_trips#invites', as: :invites

  delete 'trip-:url/leave' => 'group_trips#leave_trip', as: :leave_trip
  delete 'trip-:url/uninvite-:tag' => 'group_trips#uninvite', as: :uninvite

  delete 'trip-:url/delete' => 'trips#destroy', as: :delete_trip
  get 'trip-:url' => 'trips#show', as: :trip
  get 'trip-:url/edit' => 'trips#edit', as: :edit_trip
  post 'trip-:url/edit' => 'trips#update'
  get 'trips/new' => 'trips#new', as: :new_trip
  post 'trips/new' => 'trips#create'
  
  get 'past-trips' => 'users#past_trips', as: :past_trips
  get 'dashboard' => 'users#show', as: :dashboard
  get 'account' => 'users#edit', as: :account
  patch 'account' => 'users#update'

  post 'trip-:url/add-:title/:category/address-:address' => 'ideas#add_idea', as: :add_idea
  post 'trip-:url' => 'ideas#create', as: :new_idea
  get 'trip-:url/idea-:id' => 'ideas#show', as: :idea
  put 'trip-:url/idea-:id/edit' => 'ideas#update', as: :edit_idea
  delete 'trip-:url/idea-:id/delete' => 'ideas#destroy', as: :delete_idea
  get 'trip-:url/ideas' => 'ideas#index'

  post 'signup' => 'users#create'
  post 'login' => 'users#authenticate'
  delete 'logout' => 'users#logout', as: :logout
 
  get 'password_reset' => 'password_resets#new', as: :password_reset
  post 'password_reset' => 'password_resets#create'
  get 'password_reset/:token' => 'password_resets#edit', as: :confirm_reset
  patch 'password_reset/:token' => 'password_resets#update'

  resources :users do 
    resources :trips, only: [:show, :delete] do 
      resources :ideas, only: [:show, :delete]
    end
  end

  root 'home_pages#home'


  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/idea.rb
class Idea < ActiveRecord::Base
    include ValidDates

    belongs_to :user
    belongs_to :trip
    belongs_to :group_trips, class_name: Trip
    belongs_to :idea_category

    validates :title, presence: true 
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :require_login
  respond_to :html, :json

  def find_food
   @trip = current_trips.find_by(url: params[:url])
   @idea = @trip.ideas.find(params[:id])
   @going = @trip.invites.where(going?: true) # for header

   location = @trip.city + " " + @trip.country
   search_params ||= api_params(params[:neighborhood],
                              location, location)
   sort ||= api_params(params[:sort], 0, 0)

   yelp_api(search_params, 'restaurants', sort)
  end

  def find_events
    @trip = current_trips.find_by(url: params[:url])
    @idea = @trip.ideas.find(params[:id])
    @going = @trip.invites.where(going?: true)

    location = @trip.city + " " + @trip.country

    # TODO: sub hard-coded Foursquare category ID [currently correspond to Arts & Entertainment] for user choice! 
    category ||= api_params(params[:event_category],
                            '4d4b7104d754a06370d81259','')
    @attractions = foursquare_api(location, category)
  end

  def add_idea
    @trip = current_trips.find_by_url(params[:url])
    @idea = @trip.ideas.build(title: params[:title], location: params[:address],
                              idea_category_id: params[:category].to_i, user_id: current_user.id)
    if @idea.save
      redirect_to trip_path(@trip.url)
    else
      @errors = @idea.errors
      render :new
    end
  end

  def new
    @trip = current_trips.find_by_url(params[:url])
    @idea = @trip.ideas.build
  end

  def create
    @trip = current_trips.find_by_url(params[:url])
    @idea = @trip.ideas.build(idea_params)
    @action = 'create'
    if @idea.save
        redirect_to trip_path(@trip.url)
    else
        @errors = @idea.errors
        render :new
    end
  end

  def index
    @trip = current_trips.find_by_url(params[:url])
    @ideas = getIdeas(@trip)
    render json: @ideas
  end

  def show
    @trip = current_trips.find_by(url: params[:url])
    @idea = @trip.ideas.find(params[:id])
  end

#    def edit
#        @trip = current_trips.find_by_url(params[:url])
#        @idea = @trip.ideas.find(params[:id])
#        @action = 'edit'
#    end

  def update
    @action = 'update'
    @trip = current_trips.find_by(url: params[:url])
    @idea = @trip.ideas.find(params[:id])

    if @idea.update_attributes(idea_params)
      respond_with @idea
    else
      @errors = @trip.errors
      redirect_to trip_path(@trip.url)
    end
  end

  def destroy
    @trip = current_trips.find_by(url: params[:url])
    @idea = @trip.ideas.find(params[:id])
    @idea.destroy
    redirect_to trip_path(@trip.url)
  end

  private
    def idea_params
      params.require(:idea).permit(:title, :start_date,
                                   :end_date, :start_time,
                                   :end_time, :location,
                                   :notes, :idea_category_id,
                                   :user_id, :trip_id)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
    def idea_user(idea)
        user = User.find_by(id: idea.user_id)
        user.present? ? user : ''
    end

    def display_idea(*info)
        if info.length === 1
            info[0].present? ? info[0] : "n/a"
        else
            result = []
            info.each do |i|
                i.present? ? result << i : result << "n/a"
            end
            result.join(" to ")
        end
    end
end

app/views/ideas/_idea_form.erb
<%= form_for(:idea, url: getPath('ideas', @action)) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.collection_select :idea_category_id, IdeaCategory.all, :id, :name, {:prompt=>'Category'},{:class=>'form-control'} %>
      <%= f.text_field :title, class: 'form-control', placeholder: 'What', :required => true %> 
  
      <%= f.text_field :start_date, class: 'date-picker form-control', placeholder: 'Start Date', :required => true %>

      <%= f.text_field :start_time, class: 'time-picker form-control', placeolder: 'Time' %>

      <%= f.text_field :end_date, class: 'date-picker form-control', placeholder: 'End Date', :required => true %>
      <%= f.text_field :end_time, class: 'time-picker form-control', placeholder: 'Time' %>     

      <%= f.text_field :location, class: 'form-control form-control', placeholder: 'Where', :required => true %>
    
      <%= f.text_area :notes, rows: 3, class: 'form-control', placeholder: 'Details' %>

    <%= f.submit "Submit", class: 'btn btn-green' %>
<% end %>
    

app/views/ideas/_ideas.erb
<div class="trip--fav_action" role="group" aria-label="...">
    <ul  class="nav nav-pills nav-justified">
        <li ng-class="{'active':tab.isSet(1)}">
            <a href ng-click="tab.setTab(1)">Food</a></li>
        <li ng-class="{'active':tab.isSet(2)}">
            <a href ng-click="tab.setTab(2)">Activities</a></li>
        <li ng-class="{'active':tab.isSet(3)}">
            <a href ng-click="tab.setTab(3)">Events</a></li>
    </ul>
</div>

<div class="trip--list">           
    <div class="list-group" ng-show="tab.isSet(1)">  
        <% if !@food.empty? %>             
            <% @food.each do |idea| %>
                <%= render partial: 'ideas/section', locals: {idea: idea} %>
            <% end %>
        <% else %>
            <p style="padding:10px 15px">Nothing planned. Add your idea</p>
        <% end %>
    </div>

    <div class="list-group" ng-show="tab.isSet(2)">
        <% if !@activity.empty? %>
            <% @activity.each do |idea| %>
                <%= render partial: 'ideas/section', locals: {idea: idea} %>
            <% end %>
        <% else %>
            <p style="padding:10px 15px">Nothing planned. Add your idea</p>
        <% end %>
    </div>
             
    <div class="list-group" ng-show="tab.isSet(3)">
        <% if !@event.empty? %>
             <% @event.each do |idea| %>
                 <%= render partial: 'ideas/section', locals: {idea: idea} %>
            <% end %>
        <% else %>
            <p style="padding:10px 15px">Nothing planned. Add your idea</p>
       <% end %>
    </div>

    <button class="idea--form_action btn btn-green">Add + </button>
</div>

app/views/ideas/_section.erb
 <div class="list-group-item">
    <h4 class="list-group-item-heading">
        <%= best_in_place idea, :title, as: :input, url: edit_idea_path(@trip.url, idea.id) %>
    </h4>

    <% if current_user === idea_user(idea) || current_user === creator(@trip) %>
        <%= link_to "delete", delete_idea_path(@trip.url, idea.id), method: :delete, data: {confirm: "You sure?"}, class: "badge btn-green"  %>
        <%= link_to "edit", edit_idea_path(@trip.url, idea.id), class: "badge btn-green" %>
        <p class="list-group-item-text">
    <% end %>


    When: <%= best_in_place idea, :start_date, as: :date, url: edit_idea_path(@trip.url, idea.id) %> 
          -  <%= best_in_place idea, :end_date, as: :date, url: edit_idea_path(@trip.url, idea.id) %><br>

    Where: <%= best_in_place idea, :location, as: :input, url: edit_idea_path(@trip.url, idea.id) %> <br>
    Suggested by: <%= idea_user(idea).name %></p>

    <p><div ng-bind="ideaTitle"></div></p>    
</div>

app/views/ideas/edit.erb
<h1>Edit idea</h1>

<%= render 'shared/form_error' %>

<%= render 'idea_form' %>

app/views/ideas/find_events.erb
<%= render 'trips/navbar' %>
<%= render 'trips/header' %>

<section class="content">
  <div class="dashboard clearfix">
    <h1>Discover attractions & activities in <%= @trip.city %></h1>
    <%= link_to "<< Back", trip_path(@trip.url) %>
  </div>
  <p>Select category: <br/>
  <%= form_tag find_events_path(@trip.url), method: "get" do %>
    <%= radio_button_tag :attr_category, "4d4b7104d754a06370d81259" %>
    <%= label_tag :entertainment, "Arts & Entertainment" %>  
    <%= radio_button_tag :attr_category, "4d4b7105d754a06373d81259" %>
    <%= label_tag :events, "Events" %>  
    <%= radio_button_tag :attr_category, "4d4b7105d754a06376d81259" %>
    <%= label_tag :nightlife, "Nightlife" %>
    <%= radio_button_tag :attr_category, "4d4b7105d754a06377d81259" %>
    <%= label_tag :outdoors, "Outdoors & Recreation" %><br/>
    <%= radio_button_tag :attr_category, "4bf58dd8d48988d163941735" %>
    <%= label_tag :parks, "Parks" %>
    <%= radio_button_tag :attr_category, "4bf58dd8d48988d165941735" %>
    <%= label_tag :scenery, "Scenic Lookouts" %>
    <%= radio_button_tag :attr_category, "4d4b7105d754a06378d81259" %>
    <%= label_tag :shopping, "Shopping" %>
    <br/><%= submit_tag "Search" %>
  <% end %> 
  </p>

  <% @attractions.each do |item| %> 
    <p>
      <h2><%= item['name'] %></h2>
      <%= safe_join(item['location']['formattedAddress'], '<br>'.html_safe) %><br/>
      Category: <%= item['categories'][0]['name'] %><br/>
      
      <% if @trip.ideas.find_by_title(item['name']) %>
        <strong>ADDED</strong><br/>
      <% else %>
        <%= button_to "Add to itinerary", add_idea_path(@trip.url, item['name'], 4, item['location']['formattedAddress']), data: {confirm: "Add to itinerary?"} %>
      <% end %>
    </p>
  <% end %> 
</section>

app/views/ideas/find_food.erb
<%= render 'trips/navbar' %>
<%= render 'trips/header' %>

<section class="content">
<div class="dashboard clearfix">
<h2>Discover Restaurants in <%= @trip.city %></h2>
    <div>
    <%= form_tag find_food_path(@trip.url), method: "get" do %>
        <%= text_field_tag(:neighborhood, "", placeholder: "Neighborhood") %>
        <%= text_field_tag(:cuisine, "", placeholder: "Cuisine") %>
        <%= submit_tag "Search" %> 
    <% end %> 

    </div>

    <p>Sort results by:</p> 
    <%= form_tag find_food_path(@trip.url), method: "get" do %>  
        <%= radio_button_tag(:sort, 0) %>
        <%= label_tag(:relevance, "Relevance") %>
        <%= radio_button_tag(:sort, 1) %>
        <%= label_tag(:distance, "Distance") %>
        <%= radio_button_tag(:sort, 2) %>
        <%= label_tag(:rating, "Rating") %>
        <%= submit_tag "Sort" %> 
    <% end %> 

    <% if !@yelp_error.nil? %>
        <div class="error"> <%= @yelp_error %></div>
    <% else%> 

    
    <table class="discover_yelp">
        <tbody>
         <tr>
        <% @result.businesses.each_with_index do |b, index| %>

        <% if index != 0 && index % 5 === 0 %>
            </tr>
            <tr>
        <% end %>

            <td class="yelp_restaurant">
            <figure style="width:200px"><%= image_tag(b.image_url, alt: "#{b.name}") %> </figure>

            <h3><%= b.name %></h3>  <!-- [ <#%= b.is_closed ? "CLOSED" : "OPEN" %> ] -->
            <span>Rating: <%= b.rating %></span>

            <%= safe_join(b.location.display_address, '<br>'.html_safe) %> 

            Neighborhood: <%#= safe_join(b.location.neighborhoods, ','.html_safe) %>  

            <% if @trip.ideas.find_by_title(b.name) %>
                <strong>ADDED</strong><br/>
            <% else %>
                <%= button_to "Add to itinerary", add_idea_path(@trip.url, b.name, 1, b.location.display_address), method: :post, data: {confirm: "Add to itinerary?"} %> 
            <% end %> 

            </td>
        <% end %> 
        </tr>
        </tbody>
    </table>
<% end %>
</div>
</section>

app/views/ideas/new.erb
<h1>New Idea</h1>
<%= render 'shared/form_error' %>
<%= render 'idea_form' %>

app/views/ideas/scenery.erb
<%= render 'trips/navbar' %>
<%= render 'trips/header' %>
<h1><%= @trip.city %> on Instagram</h1>
<%= @scenery.inspect %>

app/views/ideas/show.erb
<h1><%= @idea.title %></h1>
Suggested by: <%= @idea.user.name %> <br>
Category: <%= @idea.idea_category.name %><br>
Suggested day: <%= display_idea(@idea.start_date, @idea.end_date) %><br>
Suggested time: <%= display_idea(start_t, end_t) %><br>
Location: <%= display_idea(@idea.location) %><br>
Additional details: <%= display_idea(@idea.notes) %>

<p><%= button_to "Back", trip_path(@trip.url), method: 'get', class: 'btn' %></p>