config/routes.rb
Rails.application.routes.draw do
  get 'all-timezones' => 'trips#timezones'
  get 'trip-:url/find-events' => 'ideas#find_events', as: :find_events
  get 'trip-:url/find-food' => 'ideas#find_food', as: :find_food
  get 'trip-:url/scenery' => 'ideas#scenery', as: :scenery

  get 'trip-:url/invite' => 'group_trips#invite', as: :invite_friend
  post 'trip-:url/invite' => 'group_trips#send_invite'
  patch 'trip-:url/:response' => 'group_trips#rsvp', as: :rsvp
  get 'invites' => 'group_trips#invites', as: :invites

  delete 'trip-:url/leave' => 'group_trips#leave_trip', as: :leave_trip
  delete 'trip-:url/uninvite-:tag' => 'group_trips#uninvite', as: :uninvite

  delete 'trip-:url/delete' => 'trips#destroy', as: :delete_trip
  get 'trip-:url' => 'trips#show', as: :trip
  get 'trip-:url/edit' => 'trips#edit', as: :edit_trip
  post 'trip-:url/edit' => 'trips#update'
  get 'trips/new' => 'trips#new', as: :new_trip
  post 'trips/new' => 'trips#create'
  
  get 'past-trips' => 'users#past_trips', as: :past_trips
  get 'dashboard' => 'users#show', as: :dashboard
  get 'account' => 'users#edit', as: :account
  patch 'account' => 'users#update'

  post 'trip-:url/add-:title/:category/address-:address' => 'ideas#add_idea', as: :add_idea
  post 'trip-:url' => 'ideas#create', as: :new_idea
  get 'trip-:url/idea-:id' => 'ideas#show', as: :idea
  put 'trip-:url/idea-:id/edit' => 'ideas#update', as: :edit_idea
  delete 'trip-:url/idea-:id/delete' => 'ideas#destroy', as: :delete_idea
  get 'trip-:url/ideas' => 'ideas#index'

  post 'signup' => 'users#create'
  post 'login' => 'users#authenticate'
  delete 'logout' => 'users#logout', as: :logout
 
  get 'password_reset' => 'password_resets#new', as: :password_reset
  post 'password_reset' => 'password_resets#create'
  get 'password_reset/:token' => 'password_resets#edit', as: :confirm_reset
  patch 'password_reset/:token' => 'password_resets#update'

  resources :users do 
    resources :trips, only: [:show, :delete] do 
      resources :ideas, only: [:show, :delete]
    end
  end

  root 'home_pages#home'


  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
    include ValidEmails

    has_many :invites, class_name: "Relationship",
                        foreign_key: "user_id",
                        dependent: :destroy
    has_many :trips, through: :invites

    has_many :ideas, through: :trips

    has_secure_password

    validates :name, :email, :password, presence: true, on: :create
    validates :name, length: { maximum: 50 }

    validates :password, confirmation: true,
                         length: { in: 6..15 },
                         allow_nil: true

    validates :email, :tag, uniqueness: true

    after_create :gen_user_tag

    def gen_user_tag
        num = (User.count + 1 )* 9999
        update_column :tag, SecureRandom.random_number(num)
        retries = 5
    rescue ActiveRecord::RecordNotUnique => e
        retries -= 1
        retry if retries > 0
        raise e, "An error has occurred, try again later"
    end

    def self.authenticate(email, password)
        user = User.find_by(email: email)
        if user.present? && user.authenticate(password)
            user
        end
    end

    def self.registered?(user)
        user = User.find_by(email: user.email)
        user.present?
    end

    def generate_token(column)
        begin
            self[column]= SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end

    def send_password_reset
        generate_token(:password_reset_token)
        self.password_reset_sent_at = Time.zone.now
        self.save
        UserMailer.password_reset(self).deliver
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update, :destroy, :show]
  before_action :require_logout, only: [:new, :create]

  def login
  end

  def authenticate
    @current_user = User.authenticate(params[:email], params[:password])
    if @current_user
            login_user(@current_user)
    else
        flash[:danger] = "Wrong email/password combination"
        redirect_to root_path
    end
  end

  def logout
      session.delete(:user_id)
      flash[:success] = "Logged out successfully"
      redirect_to root_path
  end

  def new
      @user = User.new
      @action = 'new' # getPath helper
  end

  def create
    @user = User.new(user_params)
    @action = 'create'
    if @user.save
        login_user(@user)
    else
        @errors = @user.errors
        render :new
    end
  end

  def show
    @created_trips = current_user.trips.where(ended?: nil)
    @invites = current_user.invites
    @pending = @invites.where(rsvped?: nil)
    @invited_trips = @invites.where(rsvped?: true)
    @action = 'create'
  end

  def past_trips
    @invites = current_user.invites
    @ended_trips = current_user.trips.where(ended?: true)
  end


  def edit
    @action = 'edit'
  end

  def update
    @action = 'update'
    if current_user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to dashboard_path
    else
        @errors = current_user.errors
        render :edit
    end
  end

  def destroy
    current_user.destroy
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email,
                                   :password, :tag,
                                   :password_confirmation
                                   )
    end
end

app/helpers/user_helper.rb
module UserHelper
 def which_user
    if current_page?(controller: 'users', action: 'edit') || !@current_user.nil?
        @current_user
    elsif current_page?(controller: 'home_pages', action: 'home') || @user.errors
        @user
    end
 end
 
end

app/views/users/_login.erb
<h1>Login</h1>

<%= form_tag "/login" do %> 
    <%= text_field_tag(:email, "", placeholder: "Email") %><br>
    <%= password_field_tag(:password, "", placeholder: "Password") %>

    <p><%= submit_tag "Login" %></p>


<% end %> 

<p><%= link_to 'forgot your password?', password_reset_path %></p> 

app/views/users/_nav.erb
<aside>
	<ul class="list-group"o>
		<li class="list-group-item"><%= link_to "Trips", dashboard_path %></li>
		<li class="list-group-item"><%= link_to "Past Trips", past_trips_path %></li>
        <li class="list-group-item"><%= link_to "Account info", account_path %></li>
        <li class="list-group-item"><%= link_to "Trip invites", invites_path %></li>
	</ul>
</aside>

app/views/users/_user_form.erb
<%= render 'shared/form_error' %>

<%= form_for(which_user, url: getPath('users', @action)) do |f| %>
    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1"><%= f.label :name %></span>
      <%= f.text_field :name, class: 'form-control'%>
    </div>

    <div class="input-group">
      <span class="input-group-addon" id="basic-addon2"><%= f.label :email %></span>
      <%= f.text_field :email, class: 'form-control'%>
    </div>
    
    <% if @action === 'new' || @action === 'create' %>
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon3"><%= f.label :password %></span>
          <%= f.password_field :password, class: 'form-control'%>
        </div>

        <div class="input-group">
          <span class="input-group-addon" id="basic-addon4"> <%= f.label :password_confirmation %></span>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <p><%= f.submit "Sign up" , class: 'btn' %></p>
    <% else %>
        <p><%= f.submit "Update info" , class: 'btn' %></p>
    <% end %>
<% end %> 

<p>
    <% if @action === 'edit' || @action === 'update' %>
       <h2>Change Password</h2>

        <%= form_for(which_user, url: getPath('users', @action)) do |f| %>

        <div class="input-group">
          <span class="input-group-addon" id="basic-addon5"><%= f.label :password %></span>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="input-group">
          <span class="input-group-addon" id="basic-addon6"> <%= f.label :password_confirmation %></span>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <p><%= f.submit "Change Password" , class: 'btn' %></p>
    <% end %>

    <p>
        <%= button_to "Delete account", current_user, method: :delete, data: {confirm: "You sure?"}, class: 'btn-danger' %>
    <% end %>
    </p>
</p>

app/views/users/edit.erb
<nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    </ul>
</nav>
<%= render 'shared/flash_msg' %>
<div class="user-profile content clearfix">
	<aside>
		<ul class="list-group">
			<li class="list-group-item"><%= link_to "Trips", dashboard_path %></li>
			<li class="list-group-item">Past Trips</li>
      <li class="list-group-item"><%= link_to "Account info", account_path %></li>
		</ul>
	</aside>
  
  <section class="content">
  	<h1>Account Information</h1>
    <%= render 'user_form' %>
  </section>

app/views/users/new.erb
<h1>Sign Up</h1>

<%= render 'user_form' %>

app/views/users/past_trips.erb
<nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    </ul>
</nav>

<div class="user-profile clearfix">
    <%= render 'nav' %>
    
    <section class="content">
        <div class="list-group user_trips">
            
            <h2>Past Trips</h2>
            <% @ended_trips.each do |trip| %>
                <% if getInvite(trip).going? %> 

                    <div class="list-group-item clearfix">
                        <h2><%= link_to "#{trip.name}", trip_path(trip.url) %> </h2>
                        <p><%= "#{format_date(trip.start_date)} to #{format_date(trip.end_date)}" %> </p>
                        <p><%= "#{trip.city},#{trip.country} " %> </p>
                        <%= headcount(trip) %> went
                    </div>

                <% end %> 
            <% end %> 

        </div>
    </section>
</div>

app/views/users/show.erb
<nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    </ul>
</nav>

<%= render 'shared/flash_msg' %>

<div class="user-profile clearfix">
    <%= render 'nav' %>

    <section class="content">
        <div class="list-group user_trips">
            <div class="list-group-item clearfix">
            <% if @pending %>
                <% @pending.each do |invite| %> 
                    <h2>Pending Invites</h2>
                       <p>
                       <h3><%= invite.trip.name %></h3>
                       <%= getSender(invite).name %> invites you</p>
                       <%= render partial: 'trips/rsvp', locals: {invite: invite} %>
                    <% end %>
            <% else %>
                No pending invites
            <% end %>
            </div>

            <% @created_trips.each do |trip| %>
                <% if creator?(nil,trip) %>
                    <div class="list-group-item clearfix">
                        <figure><a href="<%= trip_path(trip.url) %>"><img src="http://loremflickr.com/320/240"/></a></figure>
                    <h2><%= link_to "#{trip.name}", trip_path(trip.url) %> </h2>
                    <p><%= "#{format_date(trip.start_date)} to #{format_date(trip.end_date)}" %> </p>
                    <p><%= "#{trip.city},#{trip.country} " %> </p>
                    <div><%= link_to 'invite people', invite_friend_path(trip.url) %> | 
                    <%= headcount(trip) %> going |
                        <%= link_to 'edit', edit_trip_path(trip.url) %> | 

                        <%= link_to 'delete', delete_trip_path(trip.url), method: :delete, data: {confirm: 'You sure?'} %></div>
                    <span class="trip-status"><%= getRSVP( getInvite(trip) ) %></span>
                  </div>
              <% end %>
            <% end %>

            <% @invited_trips.each do |invite| %>
                <% if !tripEnded?(invite.trip) && !creator?(invite) %>
                    <div class="list-group-item clearfix">
                        <figure><a href="<%= trip_path(invite.trip.url) %>"><img src="http://loremflickr.com/320/240"/></a></figure>
                        <h2><%= link_to invite.trip.name, trip_path(invite.trip.url) %></h2>
                         <p>
                            <%= "#{format_date( invite.trip.start_date )} to #{format_date( invite.trip.end_date )}" %>
                        </p>
                        <p><%= "#{invite.trip.city},#{invite.trip.country} " %> </p>
                        <p><%= headcount( invite.trip ) %> going </p>
                        <span class="trip-status"><%= render partial: 'trips/rsvp', locals: {invite: invite} %></span>
                </div>
                <% end %>
            <% end %>
        </div>
            <p><%= link_to 'Add trip', new_trip_path %> </p>
            <%= render 'trips/trip_form' %>

	</section>

    <div style="outline:1px solid black; position:absolute; bottom:0; right: 0;width: 300px"><strong>TO DO</strong>
        <ol>
            <li> Turn trip creation form into a popup</li> 
            <li><strong>CHANGES</strong>
                <li> User login & signup forms moved to landing page [views/home_pages/home.erb]</li>
                <li> Loops refactored in user dash, past trips, manage invites, and trip dash</li>
            </li>
        </ol>
    </div>
</div>